services:
  app:
    build: .
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app

  # MYSQL
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: author_ai_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    ports:
      - '3306:3306'                          
    # volumes:
    #   - db_data:/var/lib/mysql               
    #   - ./db/init:/docker-entrypoint-initdb.d 
    networks:
      - app-network

  # Графическая оболочка бд
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'                   
    environment:
      PMA_HOST: db                  
      PMA_PORT: 3306
      PMA_ARBITRARY: 1               
    depends_on:
      - db
    networks:
      - app-network